name: trivy_with_comment_and_branch

on:
  push:
    branches: [ "main", "develop", "sprint-*" ]
  pull_request:
    branches: [ "main", "develop", "sprint-*" ]
    types: [opened]

jobs:
 # build:
 #   runs-on: ubuntu-latest
  pr_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR details
        if: github.event.pull_request.base.ref == 'develop' && contains(github.event.comment.body, 'Run Tests')
        run: exit 0

  break_workflow:
    runs-on: ubuntu-latest
    needs: [pr_check]
    steps:
      - name: Break Workflow if condition not met
        if: needs.pr_check.outcome != 'success'
        run: echo "Condition not met, breaking workflow" && exit 1 

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in repo mode
        if: steps.pr_check.outcome == 'success'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        if: steps.pr_check.outcome == 'success'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
