name: trivy_with_comment_and_branch
on:
  pull_request_target:
    types: [opened]
    branches:
      - develop
    paths:
      - '**' # Include all paths

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR for specific comment and branch
        id: check_pr
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { pull_request } = context.payload;
            const branchName = pull_request.head.ref;
            const comment = pull_request.body || '';
            if (branchName === 'develop' && comment.includes('Run Tests')) {
              console.log('Specific comment found in the PR for the specific branch.');
              process.exit(0);
            } else {
              console.log('Specific comment not found in the PR or the PR is not for the specific branch.');
              process.exit(1);
            }

      - name: Run Trivy vulnerability scanner in repo mode
        if: steps.check_pr.outcome == 'success'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        if: steps.check_pr.outcome == 'success'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
